name = input("What is your name? ") 
print("hello", name)
print("We learn git")
print("Already")
print("My second time")

print("Already")
print("My second time")
print("Already")
print("My second time")